### ISSUE TITLE
交流！

### ISSUE THREAD

**Issue by XxChang** [yucicheung/CelexMatlabToolbox#1]
你好！

我在github发现了你似乎正在做着DVS方向的研究，非常有趣。和我们正在做的东西很像，可以聊聊吗？

**Comment by yucicheung** [comment]
您好！我们确实正在做DVS方向研究，欢迎交流！
有兴趣可以联系我的邮箱yucicheung@gmail.com，我会及时回复。

**Comment by math4356** [comment]
我是鹰腾的，听俊杰说他已经联系你了，哈哈

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: YuXin Zhang <notifications@github.com>
发送时间: 星期五, 十二月 14, 2018 12:28 下午
收件人: yucicheung/CelexMatlabToolbox
抄送: chang xu; Author
主题: Re: [yucicheung/CelexMatlabToolbox] 交流！ (#1)


您好！我们确实正在做DVS方向研究，欢迎交流！
有兴趣可以联系我的邮箱yucicheung@gmail.com<mailto:yucicheung@gmail.com>，我会及时回复。

―
